### ISSUE TITLE
About data preprocessing

### ISSUE THREAD

**Issue by ZQSong1997** [YangLiangwei/ConsisRec#1]
Hello, how long is the process of performing data preprocessing? It took several hours to execute 【item_ adj_ lists = build_ item_ adj_ lists(history_v_lists) 】on my machine and it hasn't been processed yet.
Or is it convenient for you to publish the preprocessed Epinions dataset (i.e. epinions. pkl)?
Thanks.

**Comment by YangLiangwei** [comment]
It takes one night for me in this step on Epinions dataset. My previou processed data is more than 100M, it is better not push into github. Give me your email, and I can send you via Email.

**Comment by zhouchen197576** [comment]
I spent the whole night processing the ciao dataset yesterday, and now I'm processing epinions, which is estimated to take longer. Since epinions has 100MB, please send me a processed data directly. My email is zhouchen197576@outlook.com
Thanks.

**Comment by ZQSong1997** [comment]
![image](https://user-images.githubusercontent.com/46641090/158509710-9d9d2d0c-6a18-4261-8f13-6efc400ae8cd.png)
您好，如果我没有判断错误的话数据集的划分是这几行代码吧。这里默认是划分60%作为训练集，如果要分配80%就手动将train那行代码的0.4改成0.2。您在Github上发布的ciao.pkl是根据60%进行划分的，没有提供80%的。
考虑到数据在划分的时候先进行了随机打乱，考虑到实验的公平性，能麻烦请您再提供一下处理后的Ciao数据集吗？
感谢！
